# .github/dependabot.yml
version: 2
updates:
  # Enable version updates for Docker (for devcontainer.json)
  - package-ecosystem: "docker"
    directory: "/.devcontainer" # Location of devcontainer.json
    schedule:
      interval: "weekly"
    # Add reviewers or assignees if desired
    # reviewers:
    #   - "your-github-username"
    # assignees:
    #   - "your-github-username"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Scan the root for workflow files in .github/workflows
    schedule:
      interval: "weekly"
    # Add reviewers or assignees if desired
    # reviewers:
    #   - "your-github-username"
    # assignees:
    #   - "your-github-username"
